### ISSUE TITLE
TypeError: signer._signTypedData is not a function

### ISSUE THREAD

**Issue by Visbin** [snapshot-labs/snapshot.js#739]
I have a problem. Use the sample code to vote. Use Web3.js.
```
const Web3 = require('web3');
const web3 = new Web3(provider)

const wallet = web3.eth.accounts.privateKeyToAccount(privateKey)
    try {
        const hub = 'https://hub.snapshot.org'; 
        const client = new snapshot.Client712(hub);
        const receipt = await client.vote(web3, wallet, {
            space: 'pistachiodao.eth',
            proposal: '0x02c3fcd64e86157d07c88e5a715ac08f57655917f8bfd5be30a99092136511ec',
            type: 'single-choice',
            choice: 1,
            reason: '',
            app: 'snapshot'
          });
          console.log(receipt)
    } catch (error) {
        console.log(error)
    }
```

Error message:

```
TypeError: signer._signTypedData is not a function
    at Client.<anonymous> (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:290:53)
    at step (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:81:23)
    at Object.next (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:62:53)
    at /Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:55:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:51:12)
    at Client.sign (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:279:16)
    at Client.<anonymous> (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:386:51)
    at step (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:81:23)
    at Object.next (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:62:53)
    at /Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:55:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:51:12)
    at Client.vote (/Users/lys/code/javascript/snapshot/node_modules/@snapshot-labs/snapshot.js/dist/snapshot.cjs.js:365:16)
    at myRun (/Users/lys/code/javascript/snapshot/snapshot-vote.js:50:38)
    at Object.<anonymous> (/Users/lys/code/javascript/snapshot/snapshot-vote.js:66:1)
```

snapshot.js/src/sign/index.tx  Code:
![image](https://user-images.githubusercontent.com/43631862/194866304-bcdb9f49-6127-4ecb-9a89-f82b2bc7351f.png)

I wonder if my web3 dependency import is wrong?

**Comment by ChaituVR** [comment]
@Visbin the first param in vote should be a provider, refer this https://docs.snapshot.org/snapshot.js#cast-a-vote
```
const web3 = new Web3Provider(window.ethereum);
```

**Comment by randomcodemachine** [comment]
> @Visbin the first param in vote should be a provider, refer this https://docs.snapshot.org/snapshot.js#cast-a-vote
> 
> ```
> const web3 = new Web3Provider(window.ethereum);
> ```

@ChaituVR any idea on how to use this Web3Provider with a local private key? searched quite a bit but still can't figure out how..

**Comment by e3243eric** [comment]
Does anyone know how to sign with a local private key? What provider do I need to use?

**Comment by ChaituVR** [comment]
Create a wallet like here https://docs.ethers.org/v5/api/signer/#Wallet and use wallet's provider

**Comment by vswee** [comment]
Using ethers provider throws error: `TypeError: e._signTypedData is not a function`

I can successfully get `await provider.getSigners()` but passing that provider to ` receipt = await client.unfollow(...` gives the TypeError

**Comment by vswee** [comment]
> Create a wallet like here https://docs.ethers.org/v5/api/signer/#Wallet and use wallet's provider

Using ethers provider throws error: TypeError: e._signTypedData is not a function

I can successfully get await provider.getSigners() but passing that provider to  receipt = await client.unfollow(... gives the TypeError

**Comment by dnmintroad** [comment]
> This is because the SDK is made for ethers-v5 not ethers-v6.
> 
> In ethers-v5 the function is `signer._signTypedData(...)` [Ethers-V5 Docs](https://docs.ethers.org/v5/api/signer/#Signer-signTypedData)
> 
> Whereas in ethers-v6, it's been renamed to `signTypedData(...)` [Ethers-V6 Docs](https://docs.ethers.org/v6/api/providers/#Signer-signTypedData)
> 
> So, to resolve your issue just install the v5 ethers like this: `npm i ethers@5.0.18`

Thanks for this, been on a wild goose hunt trying to solve this issue. Is there anything in the roadmap to upgrade this SDK to be compatible with ethers v6?

**Comment by bunnybones1** [comment]
I know this is is going to sound hacky but I was able to work around this with an object like this
```
const hackyProvider = {
  _signTypedData: provider.signTypedData.bind(provider),
}
```
